name: workout_tracker
description: A beautiful workout tracking application

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.5
  path: ^1.8.2
  lottie: ^2.3.1
  intl: ^0.18.1
  circle_bottom_navigation: ^2.0.0
  circle_nav_bar: ^2.2.0
  curved_navigation_bar: ^1.0.6 #latest version
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    # - assets/lottie/
    # - assets/icons/
